art-library:
  num-import-threads: 1

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: de.naresea.art_library_backend.model.dialect.SQLiteDialect
  datasource:
    url: "jdbc:sqlite:image-database.db"
    driver-class-name: org.sqlite.JDBC
    username: art_library_backend
    password: hdr4Z%D3kSa-Edag
    initialization-mode: always