art-library:
  tmp-directory: "./data/tmp"
  search-directory: "./data/search"

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2048MB
      max-request-size: 2048MB
  server:
    servlet:
      session:
        cookie:
          http-only: true
          secure: true